## Классификация авиакатастроф

In [1]:
from events_data_core.air_plane_crash_classification import find_matches

# === пример текста ===
text = """
Крушение авиалайнера «Saab 340» авиакомпании «Crossair» у деревни Нассенвиль.
"""

match_spans = find_matches(text)
for i, span in enumerate(match_spans, start=1):
    print(i, span)

1 Крушение авиалайнера

In [2]:
from events_data_core.air_plane_crash_classification import is_plane_crash

examples = [
    "Самолёт потерпел крушение в Камчатке.",
    "Пилоты Boeing 737 успешно совершили посадку.",
    "Вертолёт Ми-8 разбился в Алтае.",
    "Компания Airbus представила новый лайнер.",
]

for t in examples:
    print(f"{is_plane_crash(t)} → {t}")

True → Самолёт потерпел крушение в Камчатке.
False → Пилоты Boeing 737 успешно совершили посадку.
True → Вертолёт Ми-8 разбился в Алтае.
False → Компания Airbus представила новый лайнер.

In [3]:
import pandas as pd

df = pd.read_csv('../data/events/2_struct/2000-2025.csv')
df = df.sample(random_state=42, n=100)

df['plane_crash'] = df['event'].apply(is_plane_crash)

df.head()

,date_start,date_end,event,plane_crash
2124,2010-05-29,NaN,в Осло (Норвегия) прошёл финал Конкурса песни ...,False
1609,2006-10-10,NaN,Начало работы социальной сети ВКонтакте.,False
3493,2015-11-22,NaN,"В Мьянме произошёл оползень, погибли более 90 ...",False
4856,2022-11-20,NaN,внеочередные президентские выборы в Казахстане...,False
101,2000-04-21,NaN,Госдума России ратифицировала договор о полном...,False

In [4]:
df = pd.read_csv('../data/events/2_struct/2000-2025.csv')
df['plane_crash'] = df['event'].apply(is_plane_crash)
df = df[df['plane_crash'] == True]

# todo распарсить кол-во смертей в авиакатастрофах
# отдельно рассмотреть авиакатастрофы с участием высокопоставленных лиц
# todo посмотреть, все ли я нашел с помощью своих правил
df

,date_start,date_end,event,plane_crash
10,2000-01-10,NaN,Крушение авиалайнера «Saab 340» авиакомпании «...,True
43,2000-02-16,NaN,крушение грузового самолёта «Douglas DC-8-71F»...,True
98,2000-04-19,NaN,На острове Самар при заходе на посадку в аэроп...,True
167,2000-07-04,NaN,"авария Ту-154 в Салониках, никто из находивших...",True
176,2000-07-25,NaN,катастрофа сверхзвукового авиалайнера «Конкорд...,True
...,...,...,...,...
5425,2025-01-31,NaN,Катастрофа медицинского транспортного самолёта...,True
5467,2025-02-25,NaN,самолёт ВВС Судана Ан-26 разбился в жилом райо...,True
5517,2025-04-10,NaN,"вертолёт Bell 206, на борту которого находилис...",True
5595,2025-07-21,NaN,в Бангладеш военный самолёт упал на территорию...,True
5597,2025-07-24,NaN,Пассажирский самолёт Ан-24 разбился вблизи аэр...,True