In [4]:
import pandas as pd
from gensim.models import KeyedVectors

In [5]:
df = pd.read_csv('../events/2_struct/2000-2025.csv')

df.head()

   date_start date_end                                              event
0  2000-01-01      NaN                    Деноминация белорусского рубля;
1  2000-01-01      NaN  В связи с «проблемой-2000», в Иране объявлен н...
2  2000-01-01      NaN  Вступление в силу закона в Великобритании, сог...
3  2000-01-02      NaN  Крушение украинского сухогруза типа «река-море...
4  2000-01-03      NaN  Обстрел из гранатомёта территории российского ...

In [16]:
path = "../models/cc.ru.300.vec.gz"

model = KeyedVectors.load_word2vec_format(path, binary=False)

print(model.similarity("россия", "москва"))     # должно быть высоко (около 0.6–0.8)
print(model.similarity("россия", "америка"))    # ниже, чем с "москва"
print(model.most_similar("россия", topn=20))     # ближайшие слова к "россия"

KeyboardInterrupt:

In [24]:
df[:1]

   date_start date_end                            event
0  2000-01-01      NaN  Деноминация белорусского рубля;