## Классификация авиакатастроф

In [1]:
from core.air_plane_crash_classification import PlaneCrashClassifier

clf = PlaneCrashClassifier()

# === пример текста ===
text = """
Крушение авиалайнера «Saab 340» авиакомпании «Crossair» у деревни Нассенвиль.
"""

match_spans = clf.find_matches(text)
for i, (label, span) in enumerate(match_spans, start=1):
    print(i, label, "→", span)

1 PLANE_CRASH_EVENT → Крушение авиалайнера

In [2]:
examples = [
    "Самолёт потерпел крушение в Камчатке.",
    "Пилоты Boeing 737 успешно совершили посадку.",
    "Вертолёт Ми-8 разбился в Алтае.",
    "Компания Airbus представила новый лайнер.",
]

for t in examples:
    print(f"{clf.is_plane_crash(t)} → {t}")

True → Самолёт потерпел крушение в Камчатке.
False → Пилоты Boeing 737 успешно совершили посадку.
True → Вертолёт Ми-8 разбился в Алтае.
False → Компания Airbus представила новый лайнер.

In [3]:
import pandas as pd

df = pd.read_csv('../data/events/2_struct/2000-2025.csv')
df = df.sample(random_state=42, n=100)

df['plane_crash'] = clf.classify_series(df['event'])

df.head()

,date_start,date_end,event,plane_crash
584,2002-01-28,NaN,Рикардо Мадуро Хоэст вступил в должность прези...,False
1281,2004-07-19,NaN,взрыв на автобусной остановке в Воронеже. 1 че...,False
3796,2017-05-19,2017-05-21,чемпионат Европы по художественной гимнастике ...,False
3985,2018-09-09,NaN,Единый день голосования в России.,False
2803,2013-04-09,NaN,Землетрясение в иранской провинции Бушир магни...,False

In [5]:
df = pd.read_csv('../data/events/2_struct/2000-2025.csv')
df['plane_crash'] = clf.classify_series(df['event'])
df = df[df['plane_crash'] == True]
df.head(10)

,date_start,date_end,event,plane_crash
10,2000-01-10,NaN,Крушение авиалайнера «Saab 340» авиакомпании «...,True
43,2000-02-16,NaN,крушение грузового самолёта «Douglas DC-8-71F»...,True
98,2000-04-19,NaN,На острове Самар при заходе на посадку в аэроп...,True
167,2000-07-04,NaN,"авария Ту-154 в Салониках, никто из находивших...",True
176,2000-07-25,NaN,катастрофа сверхзвукового авиалайнера «Конкорд...,True
192,2000-08-23,NaN,Самолёт Airbus A320-212 авиакомпании Gulf Air ...,True
209,2000-09-16,NaN,на международной авиакосмической выставке в Ки...,True
246,2000-10-25,NaN,"катастрофа Ил-18 под Батуми, погибли 84 человека.",True
364,2001-04-01,NaN,Над территорией китайского острова Хайнань про...,True
415,2001-06-22,NaN,в Воронежской области при выполнении авиационн...,True